spring:
  mvc:
    favicon:
      enabled: false
  thymeleaf:
    cache: false
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/field?useSSL=true
    username: root
    password: 123456
  jpa:
    hibernate:
     ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      max-file-size: 50Mb
  http:
    multipart:
      max-request-size: 100Mb